import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='keywords' content='nextjsblog, blog by saddam, build with next, next, nextjs, next framework' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <Image className={styles.myImage} src="/homepage.jfif" width={237} height={158} alt="Stacklag" />
          {/* <img src="/homepage.jfif" width={237} height={158} alt="NextJS blog" /> */}
        </div>
        <h1 className={styles.title}>
          &lt;Stacklag/&gt;
        </h1>

        <div className="blogs">
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn Javascript in 2022</h3>
            <p>Some content for the blog built with Next JS.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn Javascript in 2022</h3>
            <p>Some content for the blog built with Next JS.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn Javascript in 2022</h3>
            <p>Some content for the blog built with Next JS.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  )
}
