import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='keywords' content='nextjsblog, blog by saddam, build with next, next, nextjs, next framework' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Stacklag
        </h1>
        <div className={styles.imagewrap}>
          <Image className={styles.myImage} src="/homepage.jfif" width={237} height={158} alt="NextJS blog" />
          {/* <img src="/homepage.jfif" width={237} height={158} alt="NextJS blog" /> */}
        </div>
        <p className={styles.description}>
          A blog being built in NextJS
        </p>

        <div className="blogs">
          <h2 className={styles.heading}>Popular blogs</h2>
          <div className="blogItem">
            <h3 className={styles.blogTitle}>How to learn Javascript in 2022</h3>
            <p>Some content for the blog built with Next JS.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Some content for the blog built with Next JS.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Some content for the blog built with Next JS.</p>
          </div>
        </div>
      </main>
    </div>
  )
}
